applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas', 
        views.EntryListView.as_view(),
        name='entradas-lista',
    ),  
    path(
        'entrada/<slug>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),  
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ),  
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),  
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin URL
    path('admin/', admin.site.urls),

    # Internal Apps URLs
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),

    # URLs para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    title = models.CharField('Nombre', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Titulo Nosotros', max_length=100)
    about_text = models.TextField()
    contact_email = models.EmailField('Email Contacto', blank=True, null=True)
    contact_phone = models.CharField('Telefono Contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural = 'Pagina Principal'

    def __str__(self):
        return self.title

class Suscribers(TimeStampedModel):
    email = models.EmailField()

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email

class Contact(TimeStampedModel):
    full_name = models.CharField('Nombre Completo', max_length=100)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

    def __str__(self):
        return self.full_name

applications/home/forms.py
from django import forms
from django.db import models
from django.forms import fields, widgets

from .models import Contact, Suscribers

class SubscribersForm(forms.ModelForm):

    class Meta:
        model = Suscribers
        fields = {
            'email',
        }
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo electronico...'
                }
            )
        }

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('__all__')
        

applications/home/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    TemplateView,
    CreateView
)

from applications.entrada.models import Entry
from .forms import SubscribersForm, ContactForm
from .models import Home

class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['portada'] = Entry.objects.entry_in_home()
        context['entradas_home'] = Entry.objects.entries_in_home()
        context['home'] = Home.objects.latest('created')
        context['entradas_recent'] = Entry.objects.entries_recent()
        context['form'] = SubscribersForm
        return context

class SuscriberCreateView(CreateView):
    form_class = SubscribersForm
    success_url = '.'

class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}

{% load  static %}

{% block title %}
    {{ home.title }}
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ portada.image.url }}">
                <div class="card-section">
                  <a href="{% url 'entrada_app:entry-detail' portada.slug %}"><h4>{{ portada.title }}</h4></a>
                  <p>{{ portada.resume }}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">

            {% for entry in entradas_home %}

                <div class="cell small-12 large-6">
                    <div class="card imagen-center">
                        <img src="{{ entry.image.url }}">
                        <div class="card-section">
                            <a href="{% url 'entrada_app:entry-detail' entry.slug %}"><h5>{{ entry.title | truncatechars:50 }}</h5></a>
                        </div>
                    </div>
                </div>

            {% endfor %}
            
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-12 margin-top-2 margin-bottom-3 callout secondary">
            <h5>{{ home.about_title }}</h5>
            <p>
                {{ home.about_text }}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="post" action="{% url 'home_app:add-suscription' %}">
                    {% csrf_token %}
                    <div class="cell small-12">
                        {{ form.email }}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>

        {% for entry in entradas_recent %}
            <div class="cell small-6 large-4">
                <div class="card imagen-center">
                    <img src="{{ entry.image.url }}" style="width: 300px;">
                    <div class="card-section">
                        <a href="{% url 'entrada_app:entry-detail' entry.slug %}">
                            <h4>{{ entry.title | truncatechars:50 }}</h4>
                        </a>
                        <p>{{ entry.resume | truncatechars:100 }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
       
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}