applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas', 
        views.EntryListView.as_view(),
        name='entradas-lista',
    ),  
    path(
        'entrada/<slug>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),  
    path(
        'register-suscription', 
        views.SuscriberCreateView.as_view(),
        name='add-suscription',
    ),  
    path(
        'contact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),  
]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin URL
    path('admin/', admin.site.urls),

    # Internal Apps URLs
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),

    # URLs para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    title = models.CharField('Nombre', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Titulo Nosotros', max_length=100)
    about_text = models.TextField()
    contact_email = models.EmailField('Email Contacto', blank=True, null=True)
    contact_phone = models.CharField('Telefono Contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural = 'Pagina Principal'

    def __str__(self):
        return self.title

class Suscribers(TimeStampedModel):
    email = models.EmailField()

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.email

class Contact(TimeStampedModel):
    full_name = models.CharField('Nombre Completo', max_length=100)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

    def __str__(self):
        return self.full_name

templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="post" action="{% url 'home_app:add-contact' %}">
            {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombre
                    <input type="text" placeholder="Nombre y Apellido..." name="full_name" id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="text" placeholder="Correo ..." name="email" id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="message" id="id_message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>

        <div class="medium-12 cell large-7 text-center">
          <p class="cell large-12">Otras formas de contacto</p>
          <p class="cell large-12">
            <span class="label warning">{{ email }}</span>
            <span class="label warning">{{ phone }}</span>
          </p>
        </div>

    </div>
</div>

templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="/" style="font-size: 20px; color: #0277bd;">
                Django Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{% url 'entrada_app:entradas-lista' %}">Blog</a>
                </li>

                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'users_app:user-logout' %}">Salir</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'users_app:user-login' %}">Acceder</a>
                    </li>
                    <li>
                        <a href="{% url 'users_app:user-register' %}">Registro</a>
                    </li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</header>