applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas', 
        views.EntryListView.as_view(),
        name='entradas-lista',
    ),  
    path(
        'entrada/<slug>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),  
]

applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil', 
        views.UserPageView.as_view(),
        name='perfil',
    ),  
    path(
        'add-favorito/<pk>', 
        views.AddFavoritosView.as_view(),
        name='add-favorito',
    ),  
    path(
        'delete-favorito/<pk>', 
        views.DeleteFavoritosView.as_view(),
        name='delete-favorito',
    ),  
]

blog/urls.py
"""
Proyecto Curso Django
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin URL
    path('admin/', admin.site.urls),

    # Internal Apps URLs
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),

    # URLs para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/entrada/models.py
from datetime import timedelta, datetime

from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify

from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

from .managers import EntryManager
class Category(TimeStampedModel):
    short_name = models.CharField('Nombre corto', max_length=15, unique=True)
    name = models.CharField('Nombre', max_length=50)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class Tag(TimeStampedModel):
    name = models.CharField('Nombre', max_length=20)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Entry(TimeStampedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    tag = models.ManyToManyField(Tag)
    title = models.CharField('Titulo', max_length=200)
    resume = models.TextField('Resumen')
    content = RichTextUploadingField()
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Entry')
    portada = models.BooleanField(default=False)
    show_in_home = models.BooleanField(default=False)
    slug = models.SlugField(editable=False, max_length=300)

    objects = EntryManager()

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'


    def __str__(self):
        return self.title

    
    def save(self, *args, **kwargs):
        now = datetime.now()
        total_time = timedelta(
            hours = now.hour,
            minutes = now.minute,
            seconds = now.second,
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))

        self.slug = slugify(slug_unique)

        super(Entry, self).save(*args, **kwargs)

applications/entrada/views.py
from django.shortcuts import render

from django.views.generic import (
    ListView,
    DetailView
)

from .models import Entry, Category

class EntryListView(ListView):
    template_name = 'entrada/lista.html'
    context_object_name = 'entradas'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categorias'] = Category.objects.all()
        return context

    def get_queryset(self):
        kword = self.request.GET.get('kword', '')
        category = self.request.GET.get('category', '')

        result = Entry.objects.buscar_entradas(kword, category)

        return result

class EntryDetailView(DetailView):
    model = Entry
    template_name='entrada/detail.html'

templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/entrada/detail.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ object.title }}</h3>

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8" style="min-height: 500px;">
            <div class="cell callout primary">
                <h5>Resumen:</h5>
                <p>{{ entry.resume }}</p>
            </div>
            <div>
                <p>{{ entry.content | safe }}</p>
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img src="{{ entry.image.url }}">
                <div class="card-section" style="width: 100%;">
                  <form class="blog-action" method="post" action="{% url 'favoritos_app:add-favorito' entry.id %}">
                      {% csrf_token %}
                    <button type="submit" class="button alert">Agregar a Favoritos</button>
                  </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

templates/entrada/lista.html
<!-- head para PC -->
{% extends "entrada/base_entrada.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-12 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="get">
                {% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Buscar ...">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Buscar">
                </div>
            </form>
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->
            <div class="grid-x grid-margin-x">
                {% for entry in entradas %}
                    <div class="cell small-6 large-4">
                        <div class="card imagen-center">
                            <img src="{{ entry.image.url }}">
                            <div class="card-section" style="min-height: 210px;">
                            <a href="{% url 'entrada_app:entry-detail' entry.slug %}">
                                <h4>{{ entry.title | truncatechars:50 }}</h4>
                            </a>
                            <p>{{ entry.resume | truncatechars:100 }}</p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="cell">
                        <h5>No se han encontrado resultados.</h5>
                    </div>
                {% endfor %}
            </div>
            <!-- FIN bloque de resultados de busqueda -->

        </div>
        <!-- FIN primer bloque pantalla blog -->


        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <h4>Categorias</h4>
            <ul class="vertical menu">
                <li><a href="/entradas">All</a></li>
                {% for category in categorias %}
                    <li><a href="?category={{category.short_name}}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
        {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                        </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range  %}
                        {% ifequal pagina page_obj.number  %} 
                            <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li> 
                        {% else %}
                            <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endifequal %}
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}" >Siguiente</a>
                        </li>  
                    {% endif %}
                </ul>
            </nav>
        {% endif %} 
    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}